'use client';

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { S3Image } from '@/components/studio/s3-image';
import { TourPriceBadge } from '@/components/catalogue/tour-price-badge';
import { AiDisclosureBadge } from '@/components/catalogue/ai-disclosure-badge';
import {
  audioSourceLabel,
  displayedAudioSource,
  displayedLanguages,
  humanVoiceLabel,
  isSyntheticAudioSource,
} from '@/lib/api/audio-source-policy';
import type { Tour } from '@/types/tour';

const LANG_FLAGS: Record<string, string> = {
  fr: '🇫🇷', en: '🇬🇧', es: '🇪🇸', it: '🇮🇹', de: '🇩🇪', nl: '🇳🇱', pt: '🇵🇹', ja: '🇯🇵', zh: '🇨🇳',
};

const LANG_NAMES: Record<string, string> = {
  fr: 'Français', en: 'English', es: 'Español', it: 'Italiano', de: 'Deutsch',
  nl: 'Nederlands', pt: 'Português', ja: '日本語', zh: '中文',
};

/** Emplacement du drapeau pour une langue qu'on ne sait pas illustrer — le code
 * est déjà écrit juste après, l'y répéter donnerait « ca CA ». */
const NEUTRAL_LANG_GLYPH = '🌐';

const BADGE_TOOLTIP: Record<'fr' | 'en', string> = {
  fr: "Tout ou partie de l'audio de ce parcours est généré par synthèse vocale",
  en: 'All or part of this tour audio is generated by a synthetic voice',
};

/**
 * Ordre d'affichage du menu de filtre — **pas** une liste blanche. L'ancienne
 * `SUPPORTED_AUDIO_LANGUAGES` fermait le menu : une Visite vendue en néerlandais
 * affichait sa puce mais restait introuvable au filtre. Toute langue vendue est
 * désormais sélectionnable ; celles qui ne figurent pas ici passent en fin de
 * liste, sous leur code.
 */
const LANGUAGE_DISPLAY_ORDER = ['fr', 'en', 'es', 'de', 'it', 'nl', 'pt', 'ja', 'zh'];

function compareLanguages(a: string, b: string): number {
  const rank = (lang: string) => {
    const index = LANGUAGE_DISPLAY_ORDER.indexOf(lang);
    return index < 0 ? Number.MAX_SAFE_INTEGER : index;
  };
  // Locale explicite : ce tri s'exécute au rendu serveur ET au rendu client, et
  // deux ICU différentes classeraient différemment — donc divergence d'hydratation.
  return rank(a) - rank(b) || a.localeCompare(b, 'en');
}

interface TourListWithFilterProps {
  tours: Tour[];
  citySlug: string;
  locale?: 'fr' | 'en';
}

export function TourListWithFilter({ tours, citySlug, locale = 'fr' }: TourListWithFilterProps) {
  const [filterLang, setFilterLang] = useState<string>('');

  // Langues de chaque Visite, normalisées une seule fois : puces, filtre et
  // comptes lisent la même liste, celle de ce qui est vendu.
  const languagesByTour = useMemo(() => {
    const map = new Map<string, string[]>();
    for (const tour of tours) {
      map.set(tour.id, displayedLanguages(tour.availableLanguages, tour.languageAudioTypes));
    }
    return map;
  }, [tours]);

  // Collect all available languages across tours
  const allLanguages = useMemo(() => {
    const langs = new Set<string>();
    for (const list of languagesByTour.values()) {
      for (const lang of list) {
        langs.add(lang);
      }
    }
    return [...langs].sort(compareLanguages);
  }, [languagesByTour]);

  const langsOf = (tour: Tour) => languagesByTour.get(tour.id) ?? [];

  // Filter tours by language
  const filteredTours = useMemo(() => {
    if (!filterLang) return tours;
    return tours.filter((t) => languagesByTour.get(t.id)?.includes(filterLang));
  }, [tours, filterLang, languagesByTour]);

  if (tours.length === 0) {
    return (
      <p className="text-ink-60">
        {locale === 'en' ? 'No tours are available yet.' : 'Aucune visite disponible pour le moment.'}
      </p>
    );
  }

  return (
    <>
      {/* Language filter */}
      {allLanguages.length > 1 && (
        <div className="flex flex-wrap items-center gap-2 mb-6">
          <span className="text-sm text-ink-60">
            {locale === 'en' ? 'Filter by audio language:' : 'Filtrer par langue :'}
          </span>
          <button
            onClick={() => setFilterLang('')}
            className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
              !filterLang ? 'bg-grenadine text-white' : 'bg-paper-deep text-ink-60 hover:bg-paper-deep'
            }`}
          >
            {locale === 'en' ? 'All' : 'Toutes'} ({tours.length})
          </button>
          {allLanguages.map((lang) => {
            const count = tours.filter((t) => languagesByTour.get(t.id)?.includes(lang)).length;
            return (
              <button
                key={lang}
                onClick={() => setFilterLang(filterLang === lang ? '' : lang)}
                className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                  filterLang === lang ? 'bg-grenadine text-white' : 'bg-paper-deep text-ink-60 hover:bg-paper-deep'
                }`}
              >
                {LANG_FLAGS[lang] ?? ''} {LANG_NAMES[lang] ?? lang.toUpperCase()} ({count})
              </button>
            );
          })}
        </div>
      )}

      {/* Tour cards */}
      {filteredTours.length === 0 ? (
        <p className="text-ink-60">
          {locale === 'en' ? 'No tours are available in this language.' : 'Aucune visite disponible dans cette langue.'}
        </p>
      ) : (
        <div className="space-y-6">
          {filteredTours.map((tour) => (
            <Link
              key={tour.id}
              href={`${locale === 'en' ? '/en' : ''}/catalogue/${citySlug}/${tour.slug}`}
              data-testid={`tour-card-${tour.id}`}
              className="block rounded-xl border border-line hover:shadow-md transition-shadow overflow-hidden"
            >
              <div className="flex flex-col sm:flex-row">
                <div className="relative sm:w-64 h-48 sm:h-auto bg-grenadine-soft flex-shrink-0 overflow-hidden">
                  {tour.imageUrl && tour.imageUrl.startsWith('guide-') ? (
                    <S3Image s3Key={tour.imageUrl} alt={tour.title} className="absolute inset-0 w-full h-full object-cover hover:scale-105 transition-transform duration-500" />
                  ) : tour.imageUrl ? (
                    /* eslint-disable-next-line @next/next/no-img-element */
                    <img
                      src={tour.imageUrl}
                      alt={tour.title}
                      className="absolute inset-0 w-full h-full object-cover hover:scale-105 transition-transform duration-500"
                    />
                  ) : null}
                </div>
                <div className="p-6 flex-1">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <div className="flex items-center gap-2 mb-1 flex-wrap">
                        <h2 className="text-xl font-semibold text-ink">{tour.title}</h2>
                        <TourPriceBadge tour={tour} locale={locale} />
                        <AiDisclosureBadge tourId={tour.id} locale={locale} />
                        {langsOf(tour).length > 0 && (
                          <div className="inline-flex gap-1 items-center" data-testid={`lang-flags-${tour.id}`}>
                            {langsOf(tour).slice(0, 5).map((lang) => {
                              // Une mention absente, illisible ou muette sur cette
                              // langue se lit « synthèse » : c'est la règle qui le
                              // dit, pas un test en direct sur la carte.
                              const audioType = displayedAudioSource(tour.languageAudioTypes, lang);
                              // Le libellé humain se choisit sur `'recording'`, jamais
                              // par repli sur un `null` : un `null` rendu pour une autre
                              // raison étiquetterait une synthèse « voix du guide ».
                              const mention = isSyntheticAudioSource(audioType)
                                ? audioSourceLabel(audioType, locale)
                                : humanVoiceLabel(locale);
                              const langName = LANG_NAMES[lang] ?? lang.toUpperCase();
                              return (
                                <span
                                  key={lang}
                                  data-testid={`lang-chip-${tour.id}-${lang}`}
                                  className="inline-flex items-center gap-0.5 bg-paper-deep text-ink-80 text-xs px-1.5 py-0.5 rounded-full"
                                  title={`${langName} — ${mention}`}
                                >
                                  {LANG_FLAGS[lang] ?? NEUTRAL_LANG_GLYPH}
                                  <span className="text-[10px] font-medium">{lang.toUpperCase()}</span>
                                  <span aria-hidden="true" className="text-[10px]">
                                    {isSyntheticAudioSource(audioType) ? '🤖' : '🎤'}
                                  </span>
                                  {/* Un `title` sur un <span> n'est pas lu de façon
                                      fiable, et jamais au toucher : sur une surface de
                                      divulgation, la mention existe aussi en texte. */}
                                  <span className="sr-only">{`${langName} — ${mention}`}</span>
                                </span>
                              );
                            })}
                            {langsOf(tour).length > 5 && (
                              <span className="text-xs text-ink-40">+{langsOf(tour).length - 5}</span>
                            )}
                          </div>
                        )}
                        {langsOf(tour).some((lang) =>
                          isSyntheticAudioSource(displayedAudioSource(tour.languageAudioTypes, lang)),
                        ) && (
                          <span
                            data-testid={`tts-badge-${tour.id}`}
                            className="inline-flex items-center gap-1 bg-mer-soft text-mer text-xs font-medium px-2 py-0.5 rounded-full"
                            title={BADGE_TOOLTIP[locale]}
                          >
                            <span aria-hidden="true">🤖</span> {audioSourceLabel('tts', locale)}
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-ink-60 mb-2">
                        {locale === 'en' ? 'By' : 'Par'} {tour.guideName} &middot; {tour.duration} min &middot; {tour.distance} km
                        &middot; {tour.poiCount} {locale === 'en' ? 'stops' : 'points'}
                      </p>
                    </div>
                  </div>
                  <p className="text-ink-60 line-clamp-2">{tour.shortDescription}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </>
  );
}
