/** Traductions des textes légaux existants ; les coordonnées restent dans identity.ts. */
export type AdditionalLegalLocale = 'es' | 'de' | 'it' | 'nl';
export interface LegalDocument {
  title: string;
  intro?: string;
  sections: { title: string; text: string[] }[];
}
export interface LegalPageCopy {
  legal: string; updated: string; chooseLanguage: string; changeCookies: string;
  privacyLink: string; termsLink: string; deleteLink: string;
  deletionEmail: string; emailSubject: string; emailBody: string;
  privacy: LegalDocument; terms: LegalDocument; deletion: LegalDocument;
}

export const LEGAL_PAGES: Record<AdditionalLegalLocale, LegalPageCopy> = {
  es: {
    legal: 'Información legal', updated: 'Última actualización', chooseLanguage: 'Elegir idioma', changeCookies: 'Cambiar mi elección',
    privacyLink: 'Consultar la política de privacidad', termsLink: 'Consultar las condiciones de uso', deleteLink: 'Página de solicitud de eliminación',
    deletionEmail: 'Solicitar la eliminación por correo electrónico', emailSubject: 'Solicitud de eliminación de cuenta Murmure',
    emailBody: 'Hola:\n\nSolicito la eliminación de mi cuenta Murmure.\n\nCorreo electrónico de la cuenta: \n\nGracias.',
    privacy: {
      title: 'Política de privacidad',
      intro: 'Murmure ofrece visitas guiadas de audio: una aplicación móvil para escuchar recorridos, también sin conexión, y un estudio web para creadores. Esta política explica qué datos tratamos, por qué y cómo conservas el control.',
      sections: [
        {title: '1. Responsable del tratamiento', text: ['El responsable del tratamiento es {publisher}. Contacto: {contact}.']},
        {title: '2. Datos que recopilamos', text: ['Cuenta: dirección de correo electrónico e identificador de cuenta, con autenticación mediante Amazon Cognito.', 'Pagos: nuestros proveedores procesan las compras y suscripciones (Stripe en la web; RevenueCat, Apple App Store y Google Play en el móvil). No almacenamos los datos de tu tarjeta bancaria.', 'Contenido del creador: grabaciones de audio, textos y puntos de interés, incluidos los datos de ubicación que los guías facilitan para crear un recorrido.', 'Uso: datos técnicos y estadísticas de uso, como eventos analíticos y diagnósticos, para mejorar el servicio.']},
        {title: '3. Finalidades y bases jurídicas', text: ['Tratamos tus datos para prestar el servicio y ejecutar el contrato (cuenta, reproducción de recorridos y compras); mejorar y proteger el servicio sobre la base del interés legítimo; cumplir obligaciones legales de facturación y contabilidad; y, cuando corresponda, enviar comunicaciones sujetas a tu consentimiento.']},
        {title: '4. Destinatarios y encargados del tratamiento', text: ['Recurrimos a proveedores que tratan datos por nuestra cuenta, entre ellos Amazon Web Services (alojamiento, autenticación y almacenamiento), Stripe y RevenueCat (pagos y gestión de suscripciones), así como herramientas de analítica y diagnóstico. Todos están sujetos a las garantías contractuales correspondientes.']},
        {title: '5. Plazos de conservación', text: ['Los datos se conservan durante el tiempo necesario para las finalidades descritas y después se eliminan o anonimizan.', '{retention}']},
        {title: '6. Transferencias fuera de la Unión Europea', text: ['Algunos proveedores pueden tratar datos fuera de la UE. Estas transferencias se amparan en mecanismos reconocidos, como las cláusulas contractuales tipo de la Comisión Europea o las decisiones de adecuación.']},
        {title: '7. Tus derechos', text: ['Conforme al RGPD, tienes derechos de acceso, rectificación, supresión, limitación, oposición y portabilidad, así como el derecho a establecer instrucciones sobre tus datos después del fallecimiento. Para ejercerlos, escribe a {contact}. También puedes presentar una reclamación ante {authority}.']},
        {title: 'Eliminar tu cuenta', text: ['En la aplicación Murmure, abre Ajustes, después Datos personales y selecciona Eliminar mi cuenta. Esta acción elimina permanentemente la cuenta y los datos asociados. Si ya no puedes acceder a la aplicación, utiliza {delete}.']},
        {title: '8. Cookies y almacenamiento local', text: ['El portal web utiliza el almacenamiento de tu navegador para mantener la sesión y tus preferencias. No utilizamos cookies publicitarias ni seguimiento entre sitios.', 'La medición de audiencia (Amplitude, con servidores en la Unión Europea y sin recopilar la dirección IP) solo se activa con tu consentimiento, solicitado en tu primera visita. Puedes retirarlo en cualquier momento: {cookies}.']},
        {title: '9. Seguridad', text: ['Aplicamos medidas técnicas y organizativas para proteger tus datos, como cifrado en tránsito, controles de acceso y alojamiento seguro. Ningún sistema es infalible; te recomendamos elegir una contraseña segura.']},
        {title: '10. Contacto', text: ['Para cualquier pregunta sobre esta política o tus datos, escribe a {contact}.']},
        {title: '11. Modificaciones', text: ['Podemos actualizar esta política. Los cambios sustanciales se comunicarán en esta página con una fecha de actualización revisada.']},
      ],
    },
    terms: {
      title: 'Condiciones generales de uso', sections: [
        {title: '1. Objeto', text: ['Estas condiciones regulan el acceso y el uso de la aplicación móvil y del estudio web Murmure (el Servicio), publicados por {publisher}. Al utilizar el Servicio, aceptas estas condiciones.']},
        {title: '2. Descripción del Servicio', text: ['Murmure permite a los viajeros escuchar visitas guiadas de audio, también sin conexión, y a los guías crear y publicar visitas desde el estudio web. Algunas funciones y visitas son gratuitas; otras son de pago, mediante compra individual o suscripción.']},
        {title: '3. Cuenta', text: ['Puede ser necesario crear una cuenta para acceder a determinadas funciones. Eres responsable de la exactitud de los datos facilitados y de la confidencialidad de tus credenciales. Debes tener la edad legal necesaria para contratar.']},
        {title: '4. Contenido de los guías', text: ['Los guías son responsables del contenido que crean (audio, textos y ubicaciones) y garantizan disponer de los derechos necesarios. Las visitas se moderan antes de publicarse; podemos rechazar o retirar contenido que infrinja estas condiciones o la ley. Los guías conservan todos sus derechos sobre el contenido. Al publicarlo, conceden a Murmure una licencia no exclusiva, mundial y gratuita, durante el periodo de publicación, para alojar, distribuir, traducir y adaptar técnicamente la visita dentro del Servicio. En las visitas de pago, la parte correspondiente al guía es la indicada en el estudio en el momento de la publicación y se abona según las modalidades de su espacio Ingresos.']},
        {title: '5. Propiedad intelectual', text: ['El Servicio, su marca, su diseño y sus componentes de software están protegidos. Estas condiciones no transfieren derechos de propiedad intelectual más allá de las licencias concedidas expresamente.']},
        {title: '6. Compras, suscripciones y reembolsos', text: ['Las compras móviles se procesan mediante Apple App Store o Google Play y están sujetas a sus condiciones; las compras web se procesan mediante Stripe. Las suscripciones se renuevan automáticamente hasta su cancelación en la plataforma correspondiente. Los reembolsos de compras móviles se solicitan a Apple o Google, según la tienda utilizada. Para las compras web, el contenido digital se facilita inmediatamente después del pago: conforme al artículo L221-28, 13.º, del Código de Consumo francés, aceptas el inicio inmediato de la ejecución y renuncias al derecho de desistimiento de catorce días. Si una visita comprada es defectuosa o inaccesible, escribe a {contact}: la corregiremos o te reembolsaremos.']},
        {title: '7. Uso aceptable', text: ['Te comprometes a no utilizar indebidamente el Servicio, intentar acceder sin autorización ni publicar contenido ilícito, engañoso o que vulnere los derechos de terceros.']},
        {title: '8. Responsabilidad', text: ['El Servicio se ofrece tal cual. Dentro de los límites permitidos por la ley, Murmure no responde de daños indirectos. Las visitas utilizan datos de ubicación: presta atención a tu entorno mientras te desplazas.']},
        {title: '9. Datos personales', text: ['El tratamiento de tus datos se describe en nuestra {privacy}.']},
        {title: '10. Resolución', text: ['Puedes dejar de utilizar el Servicio y solicitar la eliminación de tu cuenta en cualquier momento. Podemos suspender o cerrar el acceso en caso de incumplimiento de estas condiciones.']},
        {title: '11. Legislación aplicable y litigios', text: ['Estas condiciones se rigen por {law}. Antes de iniciar acciones se buscará una solución amistosa: escribe primero a la dirección indicada en el artículo 12. Después puedes recurrir gratuitamente a la mediación de consumo (artículos L611-1 y siguientes del Código de Consumo francés). En su defecto, son competentes los tribunales franceses, sin perjuicio de las normas imperativas aplicables a los consumidores.']},
        {title: '12. Contacto', text: ['Para cualquier consulta, escribe a {contact}.']},
      ],
    },
    deletion: {title: 'Eliminar mi cuenta', intro: 'Puedes eliminar permanentemente tu cuenta Murmure y los datos asociados.', sections: [
      {title: 'Desde la aplicación', text: ['Inicia sesión, abre Ajustes, después Datos personales y selecciona Eliminar mi cuenta. La eliminación es irreversible y recibirás una confirmación por correo electrónico.']},
      {title: 'Si ya no puedes acceder a la aplicación', text: ['Envía una solicitud desde el correo electrónico asociado a la cuenta. Verificaremos tu identidad antes de eliminarla. Los elementos que debamos conservar por obligaciones legales, como determinados datos de facturación, se mantendrán durante los plazos aplicables.']},
    ]},
  },
  de: {
    legal: 'Rechtliche Informationen', updated: 'Zuletzt aktualisiert', chooseLanguage: 'Sprache wählen', changeCookies: 'Meine Auswahl ändern',
    privacyLink: 'Datenschutzerklärung lesen', termsLink: 'Nutzungsbedingungen lesen', deleteLink: 'Seite zur Kontolöschung',
    deletionEmail: 'Löschung per E-Mail beantragen', emailSubject: 'Antrag auf Löschung meines Murmure-Kontos',
    emailBody: 'Guten Tag,\n\nich beantrage die Löschung meines Murmure-Kontos.\n\nE-Mail-Adresse des Kontos: \n\nVielen Dank.',
    privacy: {
      title: 'Datenschutzerklärung', intro: 'Murmure bietet Audiotouren: eine mobile App zum Anhören von Rundgängen, auch offline, und ein Webstudio für Tourenersteller. Diese Erklärung beschreibt, welche Daten wir verarbeiten, warum wir dies tun und wie du die Kontrolle behältst.',
      sections: [
        {title: '1. Verantwortlicher', text: ['Verantwortlich für die Datenverarbeitung ist {publisher}. Kontakt: {contact}.']},
        {title: '2. Erhobene Daten', text: ['Konto: E-Mail-Adresse und Kontokennung; die Anmeldung erfolgt über Amazon Cognito.', 'Zahlungen: Käufe und Abonnements werden von unseren Zahlungsdienstleistern verarbeitet (Stripe im Web; RevenueCat, Apple App Store und Google Play auf Mobilgeräten). Wir speichern keine Kreditkartendaten.', 'Inhalte der Tourenersteller: Audioaufnahmen, Texte und Sehenswürdigkeiten einschließlich Standortdaten, die Guides zur Erstellung einer Tour bereitstellen.', 'Nutzung: technische Daten und Nutzungsstatistiken, etwa Analyseereignisse und Diagnosedaten, zur Verbesserung des Dienstes.']},
        {title: '3. Zwecke und Rechtsgrundlagen', text: ['Wir verarbeiten Daten zur Bereitstellung des Dienstes und Erfüllung des Vertrags (Konto, Wiedergabe und Käufe), zur Verbesserung und Absicherung des Dienstes aufgrund berechtigter Interessen, zur Erfüllung gesetzlicher Pflichten (Rechnungen und Buchhaltung) und gegebenenfalls für Mitteilungen, für die deine Einwilligung erforderlich ist.']},
        {title: '4. Empfänger und Auftragsverarbeiter', text: ['Wir beauftragen Dienstleister mit der Datenverarbeitung, insbesondere Amazon Web Services für Hosting, Authentifizierung und Speicherung, Stripe und RevenueCat für Zahlungen und Abonnements sowie Analyse- und Diagnoseanbieter. Für diese gelten angemessene vertragliche Garantien.']},
        {title: '5. Speicherdauer', text: ['Daten werden so lange gespeichert, wie es für die genannten Zwecke erforderlich ist, und anschließend gelöscht oder anonymisiert.', '{retention}']},
        {title: '6. Übermittlungen außerhalb der Europäischen Union', text: ['Einige Dienstleister können Daten außerhalb der EU verarbeiten. Solche Übermittlungen beruhen auf anerkannten Mechanismen wie den Standardvertragsklauseln der Europäischen Kommission oder Angemessenheitsbeschlüssen.']},
        {title: '7. Deine Rechte', text: ['Nach der DSGVO hast du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch und Datenübertragbarkeit sowie das Recht, Anweisungen für den Umgang mit deinen Daten nach dem Tod festzulegen. Wende dich dazu an {contact}. Du kannst außerdem Beschwerde bei {authority} einlegen.']},
        {title: 'Konto löschen', text: ['Öffne in der Murmure-App Einstellungen, dann Persönliche Daten und wähle Mein Konto löschen. Dadurch werden das Konto und die zugehörigen Daten endgültig gelöscht. Wenn du nicht mehr auf die App zugreifen kannst, nutze die {delete}.']},
        {title: '8. Cookies und lokaler Speicher', text: ['Das Webportal nutzt den Browserspeicher für deine Sitzung und Einstellungen. Wir verwenden keine Werbecookies und kein seitenübergreifendes Tracking.', 'Die Reichweitenmessung über Amplitude (Server in der Europäischen Union, ohne Erfassung der IP-Adresse) wird nur mit deiner Einwilligung aktiviert, die beim ersten Besuch abgefragt wird. Du kannst sie jederzeit widerrufen: {cookies}.']},
        {title: '9. Sicherheit', text: ['Wir schützen deine Daten durch technische und organisatorische Maßnahmen, darunter Transportverschlüsselung, Zugriffskontrollen und sicheres Hosting. Kein System ist unfehlbar; wähle deshalb ein starkes Passwort.']},
        {title: '10. Kontakt', text: ['Bei Fragen zu dieser Erklärung oder deinen Daten wende dich an {contact}.']},
        {title: '11. Änderungen', text: ['Wir können diese Erklärung aktualisieren. Wesentliche Änderungen werden auf dieser Seite mit einem neuen Aktualisierungsdatum bekannt gegeben.']},
      ],
    },
    terms: {title: 'Allgemeine Nutzungsbedingungen', sections: [
      {title: '1. Gegenstand', text: ['Diese Bedingungen regeln den Zugang zur mobilen App und zum Webstudio Murmure (der Dienst) sowie deren Nutzung. Herausgeber ist {publisher}. Durch die Nutzung des Dienstes akzeptierst du diese Bedingungen.']},
      {title: '2. Beschreibung des Dienstes', text: ['Mit Murmure können Reisende Audiotouren auch offline anhören und Guides Touren im Webstudio erstellen und veröffentlichen. Einige Funktionen und Touren sind kostenlos, andere kostenpflichtig, als Einzelkauf oder Abonnement.']},
      {title: '3. Konto', text: ['Für bestimmte Funktionen kann ein Konto erforderlich sein. Du bist für die Richtigkeit deiner Angaben und die Vertraulichkeit deiner Zugangsdaten verantwortlich. Du musst das gesetzlich erforderliche Alter für einen Vertragsabschluss erreicht haben.']},
      {title: '4. Inhalte der Guides', text: ['Guides bleiben für ihre Inhalte (Audio, Texte und Standorte) verantwortlich und sichern zu, über die erforderlichen Rechte zu verfügen. Touren werden vor der Veröffentlichung geprüft; wir können Inhalte ablehnen oder entfernen, die gegen diese Bedingungen oder das Gesetz verstoßen. Guides behalten sämtliche Rechte an ihren Inhalten. Mit der Veröffentlichung erteilen sie Murmure für deren Dauer eine nicht ausschließliche, weltweite und unentgeltliche Lizenz, die Tour im Dienst zu hosten, zu verbreiten, zu übersetzen und technisch anzupassen. Bei kostenpflichtigen Touren gilt der im Studio zum Veröffentlichungszeitpunkt angezeigte Anteil für den Guide; die Auszahlung erfolgt nach den Angaben im Bereich Einnahmen.']},
      {title: '5. Geistiges Eigentum', text: ['Der Dienst, seine Marke, sein Design und seine Softwarebestandteile sind geschützt. Diese Bedingungen übertragen keine Rechte an geistigem Eigentum über ausdrücklich gewährte Lizenzen hinaus.']},
      {title: '6. Käufe, Abonnements und Erstattungen', text: ['Mobile Käufe werden über den Apple App Store oder Google Play abgewickelt und unterliegen deren Bedingungen; Webkäufe werden über Stripe verarbeitet. Abonnements verlängern sich automatisch bis zur Kündigung auf der jeweiligen Plattform. Erstattungen mobiler Käufe beantragst du beim betreffenden Store. Bei Webkäufen werden digitale Inhalte unmittelbar nach Zahlung bereitgestellt: Gemäß Artikel L221-28 Nr. 13 des französischen Verbrauchergesetzbuchs stimmst du dem sofortigen Beginn der Ausführung zu und verzichtest auf das vierzehntägige Widerrufsrecht. Ist eine gekaufte Tour fehlerhaft oder nicht zugänglich, schreibe an {contact}; wir beheben den Fehler oder erstatten den Kaufpreis.']},
      {title: '7. Zulässige Nutzung', text: ['Du verpflichtest dich, den Dienst nicht zweckwidrig zu verwenden, keinen unbefugten Zugriff zu versuchen und keine rechtswidrigen, irreführenden oder die Rechte Dritter verletzenden Inhalte zu veröffentlichen.']},
      {title: '8. Haftung', text: ['Der Dienst wird im bestehenden Zustand bereitgestellt. Soweit gesetzlich zulässig haftet Murmure nicht für mittelbare Schäden. Touren verwenden Standortdaten: Achte unterwegs stets auf deine Umgebung.']},
      {title: '9. Personenbezogene Daten', text: ['Die Verarbeitung deiner Daten ist in unserer {privacy} beschrieben.']},
      {title: '10. Beendigung', text: ['Du kannst die Nutzung jederzeit beenden und die Löschung deines Kontos beantragen. Bei Verstößen gegen diese Bedingungen können wir den Zugang aussetzen oder schließen.']},
      {title: '11. Anwendbares Recht und Streitigkeiten', text: ['Es gilt {law}. Vor rechtlichen Schritten wird eine gütliche Einigung angestrebt; wende dich zunächst an die in Artikel 12 genannte Adresse. Anschließend kannst du die kostenlose Verbraucherschlichtung nach Artikel L611-1 ff. des französischen Verbrauchergesetzbuchs nutzen. Andernfalls sind die französischen Gerichte zuständig, vorbehaltlich zwingender Verbraucherschutzvorschriften.']},
      {title: '12. Kontakt', text: ['Bei Fragen wende dich an {contact}.']},
    ]},
    deletion: {title: 'Mein Konto löschen', intro: 'Du kannst dein Murmure-Konto und die zugehörigen Daten dauerhaft löschen.', sections: [
      {title: 'In der App', text: ['Melde dich an, öffne Einstellungen, dann Persönliche Daten und wähle Mein Konto löschen. Die Löschung ist unwiderruflich; du erhältst eine Bestätigung per E-Mail.']},
      {title: 'Wenn du nicht mehr auf die App zugreifen kannst', text: ['Sende die Anfrage von der E-Mail-Adresse deines Kontos. Wir prüfen deine Identität vor der Löschung. Daten, die wir aufgrund gesetzlicher Pflichten aufbewahren müssen, etwa bestimmte Rechnungsdaten, bleiben für die geltenden Fristen gespeichert.']},
    ]},
  },
  it: {
    legal: 'Informazioni legali', updated: 'Ultimo aggiornamento', chooseLanguage: 'Scegli la lingua', changeCookies: 'Modifica la mia scelta',
    privacyLink: 'Leggi l’informativa sulla privacy', termsLink: 'Leggi le condizioni d’uso', deleteLink: 'pagina di richiesta di eliminazione',
    deletionEmail: 'Richiedi l’eliminazione via e-mail', emailSubject: 'Richiesta di eliminazione dell’account Murmure',
    emailBody: 'Buongiorno,\n\nchiedo l’eliminazione del mio account Murmure.\n\nIndirizzo e-mail dell’account: \n\nGrazie.',
    privacy: {title: 'Informativa sulla privacy', intro: 'Murmure offre visite guidate audio: un’app mobile per ascoltare itinerari anche offline e uno studio web per i creatori. Questa informativa spiega quali dati trattiamo, perché e come mantieni il controllo.', sections: [
      {title: '1. Titolare del trattamento', text: ['Il titolare del trattamento è {publisher}. Contatto: {contact}.']},
      {title: '2. Dati raccolti', text: ['Account: indirizzo e-mail e identificativo dell’account, con autenticazione tramite Amazon Cognito.', 'Pagamenti: acquisti e abbonamenti sono gestiti dai nostri fornitori (Stripe sul web; RevenueCat, Apple App Store e Google Play su mobile). Non conserviamo i dati della carta bancaria.', 'Contenuti dei creatori: registrazioni audio, testi e punti di interesse, compresi i dati di posizione forniti dalle guide per creare un itinerario.', 'Utilizzo: dati tecnici e statistiche di utilizzo, come eventi analitici e diagnostica, per migliorare il servizio.']},
      {title: '3. Finalità e basi giuridiche', text: ['Trattiamo i dati per fornire il servizio ed eseguire il contratto (account, ascolto degli itinerari e acquisti), migliorare e proteggere il servizio sulla base del legittimo interesse, rispettare obblighi legali di fatturazione e contabilità e, ove previsto, inviare comunicazioni soggette al tuo consenso.']},
      {title: '4. Destinatari e responsabili del trattamento', text: ['Utilizziamo fornitori che trattano dati per nostro conto, tra cui Amazon Web Services per hosting, autenticazione e archiviazione, Stripe e RevenueCat per pagamenti e abbonamenti, oltre a strumenti di analisi e diagnostica. Sono tutti soggetti ad adeguate garanzie contrattuali.']},
      {title: '5. Tempi di conservazione', text: ['I dati sono conservati per il tempo necessario alle finalità descritte, poi eliminati o anonimizzati.', '{retention}']},
      {title: '6. Trasferimenti fuori dall’Unione europea', text: ['Alcuni fornitori possono trattare dati fuori dall’UE. Tali trasferimenti sono disciplinati da meccanismi riconosciuti, come le clausole contrattuali tipo della Commissione europea o le decisioni di adeguatezza.']},
      {title: '7. I tuoi diritti', text: ['Ai sensi del GDPR hai diritto di accesso, rettifica, cancellazione, limitazione, opposizione e portabilità dei dati, nonché di stabilire istruzioni sul loro trattamento dopo la morte. Per esercitarli, scrivi a {contact}. Puoi anche presentare un reclamo presso {authority}.']},
      {title: 'Eliminare l’account', text: ['Nell’app Murmure, apri Impostazioni, poi Dati personali e scegli Elimina il mio account. L’operazione elimina definitivamente l’account e i dati associati. Se non puoi più accedere all’app, usa la {delete}.']},
      {title: '8. Cookie e archiviazione locale', text: ['Il portale web utilizza la memoria del browser per mantenere la sessione e le preferenze. Non utilizziamo cookie pubblicitari né tracciamento tra siti.', 'La misurazione del pubblico (Amplitude, con server nell’Unione europea e senza raccolta dell’indirizzo IP) si attiva solo con il tuo consenso, richiesto alla prima visita. Puoi revocarlo in qualsiasi momento: {cookies}.']},
      {title: '9. Sicurezza', text: ['Adottiamo misure tecniche e organizzative per proteggere i dati, tra cui cifratura durante il trasferimento, controlli di accesso e hosting sicuro. Nessun sistema è infallibile: scegli una password robusta.']},
      {title: '10. Contatto', text: ['Per domande su questa informativa o sui tuoi dati, scrivi a {contact}.']},
      {title: '11. Modifiche', text: ['Possiamo aggiornare questa informativa. Le modifiche sostanziali saranno comunicate su questa pagina con una nuova data di aggiornamento.']},
    ]},
    terms: {title: 'Condizioni generali d’uso', sections: [
      {title: '1. Oggetto', text: ['Queste condizioni disciplinano l’accesso e l’utilizzo dell’app mobile e dello studio web Murmure (il Servizio), pubblicati da {publisher}. Utilizzando il Servizio accetti queste condizioni.']},
      {title: '2. Descrizione del Servizio', text: ['Murmure consente ai viaggiatori di ascoltare visite guidate audio anche offline e alle guide di creare e pubblicare visite tramite lo studio web. Alcune funzioni e visite sono gratuite, altre a pagamento, tramite acquisto singolo o abbonamento.']},
      {title: '3. Account', text: ['Per alcune funzioni può essere necessario creare un account. Sei responsabile dell’esattezza delle informazioni fornite e della riservatezza delle credenziali. Devi avere l’età legale richiesta per stipulare un contratto.']},
      {title: '4. Contenuti delle guide', text: ['Le guide restano responsabili dei contenuti che creano (audio, testi e posizioni) e garantiscono di possedere i diritti necessari. Le visite sono moderate prima della pubblicazione; possiamo rifiutare o rimuovere contenuti che violino queste condizioni o la legge. Le guide conservano tutti i diritti sui propri contenuti. Pubblicandoli, concedono a Murmure una licenza non esclusiva, mondiale e gratuita, per la durata della pubblicazione, per ospitare, distribuire, tradurre e adattare tecnicamente la visita nel Servizio. Per le visite a pagamento, la quota della guida è quella indicata nello studio al momento della pubblicazione e viene versata secondo le modalità della sezione Ricavi.']},
      {title: '5. Proprietà intellettuale', text: ['Il Servizio, il marchio, il design e i componenti software sono protetti. Queste condizioni non trasferiscono diritti di proprietà intellettuale oltre alle licenze espressamente concesse.']},
      {title: '6. Acquisti, abbonamenti e rimborsi', text: ['Gli acquisti su mobile sono elaborati da Apple App Store o Google Play e soggetti alle loro condizioni; gli acquisti web sono gestiti da Stripe. Gli abbonamenti si rinnovano automaticamente fino alla cancellazione tramite la relativa piattaforma. Per i rimborsi su mobile rivolgiti ad Apple o Google, secondo il negozio utilizzato. Per gli acquisti web, il contenuto digitale è disponibile subito dopo il pagamento: ai sensi dell’articolo L221-28, 13°, del Codice del consumo francese, accetti l’inizio immediato dell’esecuzione e rinunci al diritto di recesso di quattordici giorni. Se una visita acquistata è difettosa o inaccessibile, scrivi a {contact}: la correggeremo o ti rimborseremo.']},
      {title: '7. Uso consentito', text: ['Ti impegni a non usare impropriamente il Servizio, tentare accessi non autorizzati o pubblicare contenuti illeciti, ingannevoli o lesivi dei diritti di terzi.']},
      {title: '8. Responsabilità', text: ['Il Servizio è fornito così com’è. Nei limiti consentiti dalla legge, Murmure non risponde dei danni indiretti. Le visite utilizzano dati di posizione: presta attenzione all’ambiente circostante mentre ti sposti.']},
      {title: '9. Dati personali', text: ['Il trattamento dei dati è descritto nella nostra {privacy}.']},
      {title: '10. Cessazione', text: ['Puoi smettere di utilizzare il Servizio e chiedere l’eliminazione dell’account in qualsiasi momento. Possiamo sospendere o chiudere l’accesso in caso di violazione delle condizioni.']},
      {title: '11. Legge applicabile e controversie', text: ['Si applica {law}. Prima di agire legalmente si cercherà una soluzione amichevole: scrivi prima all’indirizzo indicato nell’articolo 12. Puoi poi ricorrere gratuitamente alla mediazione dei consumatori ai sensi degli articoli L611-1 e seguenti del Codice del consumo francese. In mancanza di accordo, sono competenti i tribunali francesi, fatte salve le norme imperative a tutela dei consumatori.']},
      {title: '12. Contatto', text: ['Per qualsiasi domanda, scrivi a {contact}.']},
    ]},
    deletion: {title: 'Elimina il mio account', intro: 'Puoi eliminare definitivamente il tuo account Murmure e i dati associati.', sections: [
      {title: 'Dall’app', text: ['Accedi, apri Impostazioni, poi Dati personali e scegli Elimina il mio account. L’eliminazione è irreversibile e riceverai una conferma via e-mail.']},
      {title: 'Se non puoi più accedere all’app', text: ['Invia la richiesta dall’indirizzo e-mail associato all’account. Verificheremo la tua identità prima della cancellazione. Gli elementi da conservare per obblighi legali, come alcuni dati di fatturazione, resteranno archiviati per i periodi previsti.']},
    ]},
  },
  nl: {
    legal: 'Juridische informatie', updated: 'Laatst bijgewerkt', chooseLanguage: 'Taal kiezen', changeCookies: 'Mijn keuze wijzigen',
    privacyLink: 'Privacybeleid lezen', termsLink: 'Gebruiksvoorwaarden lezen', deleteLink: 'pagina voor een verwijderverzoek',
    deletionEmail: 'Verwijdering per e-mail aanvragen', emailSubject: 'Verzoek om mijn Murmure-account te verwijderen',
    emailBody: 'Hallo,\n\nIk verzoek om verwijdering van mijn Murmure-account.\n\nE-mailadres van het account: \n\nBedankt.',
    privacy: {title: 'Privacybeleid', intro: 'Murmure biedt audiotours: een mobiele app om routes te beluisteren, ook offline, en een webstudio voor makers. Dit beleid legt uit welke gegevens we verwerken, waarom en hoe je de controle houdt.', sections: [
      {title: '1. Verwerkingsverantwoordelijke', text: ['De verwerkingsverantwoordelijke is {publisher}. Contact: {contact}.']},
      {title: '2. Gegevens die we verzamelen', text: ['Account: e-mailadres en accountidentificatie, met authenticatie via Amazon Cognito.', 'Betalingen: aankopen en abonnementen worden verwerkt door onze betaalproviders (Stripe op het web; RevenueCat, Apple App Store en Google Play op mobiel). We slaan geen bankkaartgegevens op.', 'Inhoud van makers: audio-opnamen, teksten en bezienswaardigheden, inclusief locatiegegevens die gidsen aanleveren om een route te maken.', 'Gebruik: technische gegevens en gebruiksstatistieken, zoals analysegebeurtenissen en diagnostiek, om de dienst te verbeteren.']},
      {title: '3. Doelen en rechtsgronden', text: ['We verwerken gegevens om de dienst te leveren en de overeenkomst uit te voeren (account, afspelen en aankopen), de dienst te verbeteren en beveiligen op basis van gerechtvaardigd belang, wettelijke facturatie- en boekhoudverplichtingen na te komen en, waar van toepassing, berichten te sturen waarvoor je toestemming vereist is.']},
      {title: '4. Ontvangers en verwerkers', text: ['We gebruiken dienstverleners die namens ons gegevens verwerken, waaronder Amazon Web Services voor hosting, authenticatie en opslag, Stripe en RevenueCat voor betalingen en abonnementen, en analyse- en diagnosetools. Voor hen gelden passende contractuele waarborgen.']},
      {title: '5. Bewaartermijnen', text: ['Gegevens worden bewaard zolang dat nodig is voor de beschreven doelen en daarna verwijderd of geanonimiseerd.', '{retention}']},
      {title: '6. Doorgifte buiten de Europese Unie', text: ['Sommige dienstverleners kunnen gegevens buiten de EU verwerken. Die doorgifte steunt op erkende mechanismen, zoals de standaardcontractbepalingen van de Europese Commissie of adequaatheidsbesluiten.']},
      {title: '7. Je rechten', text: ['Onder de AVG heb je recht op inzage, rectificatie, verwijdering, beperking, bezwaar en overdraagbaarheid van gegevens, en het recht om instructies vast te leggen voor je gegevens na je overlijden. Schrijf daarvoor naar {contact}. Je kunt ook een klacht indienen bij {authority}.']},
      {title: 'Je account verwijderen', text: ['Open in de Murmure-app Instellingen, vervolgens Persoonlijke gegevens en kies Mijn account verwijderen. Dit verwijdert je account en de bijbehorende gegevens definitief. Kun je de app niet meer gebruiken, ga dan naar de {delete}.']},
      {title: '8. Cookies en lokale opslag', text: ['Het webportaal gebruikt de browseropslag voor je sessie en voorkeuren. We gebruiken geen advertentiecookies of tracking tussen websites.', 'Publieksmeting via Amplitude (servers in de Europese Unie, zonder verzameling van het IP-adres) wordt alleen met je toestemming ingeschakeld. We vragen die bij je eerste bezoek. Je kunt je toestemming altijd intrekken: {cookies}.']},
      {title: '9. Beveiliging', text: ['We nemen technische en organisatorische maatregelen om je gegevens te beschermen, zoals versleuteling tijdens verzending, toegangscontrole en veilige hosting. Geen enkel systeem is onfeilbaar; kies daarom een sterk wachtwoord.']},
      {title: '10. Contact', text: ['Voor vragen over dit beleid of je gegevens kun je schrijven naar {contact}.']},
      {title: '11. Wijzigingen', text: ['We kunnen dit beleid bijwerken. Belangrijke wijzigingen worden op deze pagina gemeld met een aangepaste datum.']},
    ]},
    terms: {title: 'Algemene gebruiksvoorwaarden', sections: [
      {title: '1. Doel', text: ['Deze voorwaarden regelen de toegang tot en het gebruik van de mobiele app en webstudio Murmure (de Dienst), uitgegeven door {publisher}. Door de Dienst te gebruiken, aanvaard je deze voorwaarden.']},
      {title: '2. Beschrijving van de Dienst', text: ['Met Murmure kunnen reizigers audiotours beluisteren, ook offline, en kunnen gidsen tours maken en publiceren via de webstudio. Sommige functies en tours zijn gratis, andere zijn betaald via een losse aankoop of abonnement.']},
      {title: '3. Account', text: ['Voor bepaalde functies kan een account nodig zijn. Je bent verantwoordelijk voor de juistheid van je gegevens en de vertrouwelijkheid van je inloggegevens. Je moet de wettelijk vereiste leeftijd hebben om een overeenkomst te sluiten.']},
      {title: '4. Inhoud van gidsen', text: ['Gidsen blijven verantwoordelijk voor hun inhoud (audio, teksten en locaties) en garanderen dat zij over de nodige rechten beschikken. Tours worden vóór publicatie beoordeeld; we kunnen inhoud weigeren of verwijderen die strijdig is met deze voorwaarden of de wet. Gidsen behouden alle rechten op hun inhoud. Door te publiceren geven zij Murmure voor de duur van de publicatie een niet-exclusieve, wereldwijde, kosteloze licentie om de tour binnen de Dienst te hosten, verspreiden, vertalen en technisch aan te passen. Voor betaalde tours geldt het aandeel dat bij publicatie in de studio wordt getoond; uitbetaling gebeurt volgens de voorwaarden in het onderdeel Inkomsten.']},
      {title: '5. Intellectueel eigendom', text: ['De Dienst, het merk, het ontwerp en de softwareonderdelen zijn beschermd. Deze voorwaarden dragen geen intellectuele-eigendomsrechten over buiten uitdrukkelijk verleende licenties.']},
      {title: '6. Aankopen, abonnementen en terugbetalingen', text: ['Mobiele aankopen worden verwerkt door Apple App Store of Google Play en vallen onder hun voorwaarden; webaankopen worden verwerkt door Stripe. Abonnementen worden automatisch verlengd tot opzegging via het betreffende platform. Vraag een terugbetaling van een mobiele aankoop aan bij Apple of Google, afhankelijk van de winkel. Bij webaankopen is digitale inhoud direct na betaling beschikbaar: overeenkomstig artikel L221-28, 13°, van de Franse consumentenwet stem je in met onmiddellijke uitvoering en doe je afstand van het herroepingsrecht van veertien dagen. Is een gekochte tour defect of niet toegankelijk, schrijf dan naar {contact}: we herstellen de tour of betalen je terug.']},
      {title: '7. Aanvaardbaar gebruik', text: ['Je verbindt je ertoe de Dienst niet te misbruiken, geen onbevoegde toegang te proberen en geen onrechtmatige, misleidende of inbreukmakende inhoud te publiceren.']},
      {title: '8. Aansprakelijkheid', text: ['De Dienst wordt aangeboden in de huidige staat. Voor zover de wet dat toestaat, is Murmure niet aansprakelijk voor indirecte schade. Tours gebruiken locatiegegevens: blijf tijdens het lopen op je omgeving letten.']},
      {title: '9. Persoonsgegevens', text: ['De verwerking van je gegevens wordt beschreven in ons {privacy}.']},
      {title: '10. Beëindiging', text: ['Je kunt altijd stoppen met de Dienst en vragen je account te verwijderen. Bij overtreding van deze voorwaarden kunnen we de toegang opschorten of beëindigen.']},
      {title: '11. Toepasselijk recht en geschillen', text: ['Op deze voorwaarden is {law} van toepassing. Vóór juridische stappen zoeken we een minnelijke oplossing: schrijf eerst naar het adres in artikel 12. Vervolgens kun je gratis gebruikmaken van consumentenbemiddeling volgens artikel L611-1 en volgende van de Franse consumentenwet. Anders zijn de Franse rechtbanken bevoegd, onverminderd dwingende consumentenbeschermingsregels.']},
      {title: '12. Contact', text: ['Voor vragen kun je schrijven naar {contact}.']},
    ]},
    deletion: {title: 'Mijn account verwijderen', intro: 'Je kunt je Murmure-account en de bijbehorende gegevens definitief verwijderen.', sections: [
      {title: 'Via de app', text: ['Log in, open Instellingen, daarna Persoonlijke gegevens en kies Mijn account verwijderen. De verwijdering is onomkeerbaar en je ontvangt een bevestiging per e-mail.']},
      {title: 'Als je de app niet meer kunt gebruiken', text: ['Stuur je verzoek vanaf het e-mailadres van je account. We controleren je identiteit voordat we het account verwijderen. Gegevens die we wettelijk moeten bewaren, zoals bepaalde facturatiegegevens, blijven gedurende de toepasselijke termijnen bewaard.']},
    ]},
  },
};
